version: '3'

services:
  app:
    build: .
    environment:
    
        - PORT=8501

    volumes:
        
        - "./src:/app"
        - "./images:/app/images"
        
    ports:
        - "8501:8501"